import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/guitar.png',
    title: 'Intro to Guitar Lesson',
    rating: 5,
    ratingCount: 23,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/acuGuitar.jpg',
    title: 'Mixing and Mastering Acoustic Guitar',
    rating: 5,
    ratingCount: 13,
    price: 25,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/guitarTab.png',
    title: 'Custom Guitar Tabs',
    rating: 5,
    ratingCount: 15,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/pianoSheet.png',
    title: 'Custom Piano Tabs',
    rating: 4,
    ratingCount: 5,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/djing.png',
    title: 'Intro to DJ Lesson',
    rating: 4,
    ratingCount: 9,
    price: 35,
    category: 'Intermediate',
  },
  // {
  //   id: 6,
  //   cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
  //   title: 'Ethical Hacking Bootcamp Zero to Mastery',
  //   rating: 5,
  //   ratingCount: 14,
  //   price: 35,
  //   category: 'Beginner',
  // },
  // {
  //   id: 7,
  //   cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
  //   title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
  //   rating: 4,
  //   ratingCount: 6,
  //   price: 25,
  //   category: 'Beginner',
  // },
]
